openapi: 3.0.0

info:
  title: Pet store
  description: Pet store management system
  version: 2.0.0
  x-logo:
    url: ./logo.png
    altText: OpenAPI logo
    href: https://www.openapis.org

tags:
  - name: Pet

paths:
  /pets:
    get:
      tags:
        - Pet
      summary: List of pet
      responses:
        $ref: ./responses/@pets.yaml#/get
    post:
      tags:
        - Pet
      summary: Create new pet
      requestBody:
        $ref: ./requestBodies/@pets.yaml#/post
      responses:
        $ref: ./responses/@pets.yaml#/post
  /pets/{petId}:
    get:
      tags:
        - Pet
      summary: Update pet information
      parameters:
        $ref: ./parameters/@pets@{petId}.yaml#/get
      responses:
        $ref: ./responses/@pets@{petId}.yaml#/get
    patch:
      tags:
        - Pet
      summary: Update pet information
      parameters:
        $ref: ./parameters/@pets@{petId}.yaml#/patch
      requestBody:
        $ref: ./requestBodies/@pets@{petId}.yaml#/patch
      responses:
        $ref: ./responses/@pets@{petId}.yaml#/patch
    delete:
      tags:
        - Pet
      summary: Delete pet
      parameters:
        $ref: ./parameters/@pets@{petId}.yaml#/delete
      responses:
        $ref: ./responses/@pets@{petId}.yaml#/delete
